### ISSUE TITLE
If you have more than 1 app open in the browser, one of the apps gets the user from the other app

### ISSUE THREAD

**Issue by katchengli** [uoForms/quickforms3#9]
Originally reported by Isabella Vieira:

If I have RPP logged as Alabelle and Said logged as Admin, for example, and then I update the two apps... RPP gets admin as user and Said gets Alabelle as user.

PS: This happen even if the app doesn't have that user.... and even if the app doesn't have admin (as SEGcourse), it gets all the admin preferences (design control etc).

-- Is this problem because all the apps have the same user role? What if we change the user role for all the apps? For example, administratorRPP, userRPP, administratorSaid, userSaid...

**Comment by kaifanzhu** [comment]
Because the browser identifies the app's cookie with domain name, all the apps on the same server has the same domain name. So once an app is logged in, the browser identifies user is logged onto this site, which usually is http://localhost:8080. When the other app use getCookie(), it will get one.

Temporary solution is add another attribute like 'appName' in the cookie to identify by program "authenticate.js" is this user belong to this app. But it will still could be bypassed by fake domain name, like change hosts file.

I will patch the temporary solution next week and keep looking for more secure way.
